// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto/hello.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	grpc/proto/hello.proto

It has these top-level messages:
	HelloReq
	HelloRes
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto1.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloRes struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *HelloRes) Reset()                    { *m = HelloRes{} }
func (m *HelloRes) String() string            { return proto1.CompactTextString(m) }
func (*HelloRes) ProtoMessage()               {}
func (*HelloRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloRes) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto1.RegisterType((*HelloReq)(nil), "proto.HelloReq")
	proto1.RegisterType((*HelloRes)(nil), "proto.HelloRes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error)
	HelloList(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (Hello_HelloListClient, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Hello(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (*HelloRes, error) {
	out := new(HelloRes)
	err := grpc.Invoke(ctx, "/proto.Hello/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) HelloList(ctx context.Context, in *HelloReq, opts ...grpc.CallOption) (Hello_HelloListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Hello_serviceDesc.Streams[0], c.cc, "/proto.Hello/HelloList", opts...)
	if err != nil {
		return nil, err
	}
	x := &helloHelloListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Hello_HelloListClient interface {
	Recv() (*HelloRes, error)
	grpc.ClientStream
}

type helloHelloListClient struct {
	grpc.ClientStream
}

func (x *helloHelloListClient) Recv() (*HelloRes, error) {
	m := new(HelloRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Hello service

type HelloServer interface {
	Hello(context.Context, *HelloReq) (*HelloRes, error)
	HelloList(*HelloReq, Hello_HelloListServer) error
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Hello/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Hello(ctx, req.(*HelloReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_HelloList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HelloServer).HelloList(m, &helloHelloListServer{stream})
}

type Hello_HelloListServer interface {
	Send(*HelloRes) error
	grpc.ServerStream
}

type helloHelloListServer struct {
	grpc.ServerStream
}

func (x *helloHelloListServer) Send(m *HelloRes) error {
	return x.ServerStream.SendMsg(m)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Hello_Hello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HelloList",
			Handler:       _Hello_HelloList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpc/proto/hello.proto",
}

func init() { proto1.RegisterFile("grpc/proto/hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x03, 0xb3, 0x85,
	0x58, 0xc1, 0x94, 0x92, 0x1c, 0x17, 0x87, 0x07, 0x48, 0x34, 0x28, 0xb5, 0x50, 0x48, 0x88, 0x8b,
	0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x56, 0x92, 0x81,
	0xcb, 0x17, 0x0b, 0x09, 0x70, 0x31, 0xe7, 0x16, 0xa7, 0x43, 0xa5, 0x41, 0x4c, 0xa3, 0x74, 0x2e,
	0x56, 0xb0, 0xac, 0x90, 0x36, 0x8c, 0xc1, 0x0f, 0x31, 0x5e, 0x0f, 0x66, 0xa8, 0x14, 0x9a, 0x40,
	0xb1, 0x12, 0x83, 0x90, 0x21, 0x17, 0x27, 0x98, 0xe7, 0x93, 0x59, 0x5c, 0x42, 0x8c, 0x06, 0x03,
	0xc6, 0x24, 0x36, 0xb0, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x78, 0x42, 0xa1, 0xfa, 0xce,
	0x00, 0x00, 0x00,
}
